export interface Resource {
  id: number;
  title: string;
  type: string;
  date: string;
  time: string;
  location: string;
  address: string;
  cost: string;
  tags: string[];
  image: string;
  latitude: number;
  longitude: number;
  description: string;
  // For calendar: "wed" | "sat" | "mon-wed" | "YYYY-MM-DD"
  schedule: string;
}

export const RESOURCES: Resource[] = [
  {
    id: 1,
    title: "Sammamish Farmers Market",
    type: "Event",
    date: "Every Wednesday",
    time: "3:00 PM - 8:00 PM",
    location: "Upper Sammamish Commons",
    address: "801 228th Ave SE, Sammamish, WA 98075",
    cost: "Free Entry",
    tags: ["Community", "Food", "Family"],
    image: "https://images.unsplash.com/photo-1514583079045-e928a4732ade?w=800",
    latitude: 47.601448,
    longitude: -122.037971,
    description: "Every Wednesday afternoon, the Sammamish Commons transforms into a vibrant open-air market. Browse fresh local produce, handcrafted goods, and artisan foods from vendors across the Pacific Northwest. A beloved weekly tradition for families, neighbors, and food lovers alike.",
    schedule: "wed",
  },
  {
    id: 2,
    title: "Volunteer @ Sammamish Landing",
    type: "Volunteering",
    date: "Saturday, Feb 2, 2026",
    time: "9:00 AM - 12:00 PM",
    location: "Sammamish Landing",
    address: "4607 E Lake Sammamish Pkwy NE, Sammamish, WA 98074",
    cost: "Free",
    tags: ["Community", "Environment", "Volunteering"],
    image: "https://images.unsplash.com/photo-1652971876875-05db98fab376?w=800",
    latitude: 47.650410,
    longitude: -122.089241,
    description: "Join fellow community members for a morning of environmental stewardship at Sammamish Landing. Volunteers help with trail maintenance, shoreline cleanup, and habitat restoration. All skill levels welcome — gloves and tools provided. A great way to give back and connect with nature.",
    schedule: "2026-02-02",
  },
  {
    id: 3,
    title: "Coffee with Council",
    type: "Event",
    date: "Thursday, Jan 28, 2026",
    time: "10:00 AM - 11:30 AM",
    location: "Sammamish City Hall",
    address: "801 228th Ave SE, Sammamish, WA 98075",
    cost: "Free Entry",
    tags: ["Community", "Government", "Networking"],
    image: "https://images.unsplash.com/photo-1541167760496-1628856ab772?w=800",
    latitude: 47.601448,
    longitude: -122.037971,
    description: "An informal meet-and-greet with Sammamish City Council members over coffee. Residents are encouraged to share ideas, ask questions, and discuss local issues in a relaxed setting. Your voice shapes our community — come say hello to your representatives.",
    schedule: "2026-01-28",
  },
  {
    id: 4,
    title: "Youth Soccer Program",
    type: "Program",
    date: "Every Saturday",
    time: "10:00 AM - 12:00 PM",
    location: "Marymoor Park Field E",
    address: "6046 W Lake Sammamish Pkwy NE, Redmond, WA 98052",
    cost: "$50/month",
    tags: ["Youth", "Sports", "Recreation"],
    image: "https://images.unsplash.com/photo-1551958219-acbc608c6377?w=800",
    latitude: 47.661770,
    longitude: -122.125977,
    description: "A weekly recreational soccer program for youth ages 6–14 at the beautiful Marymoor Park fields. Led by experienced coaches, the program focuses on skill development, teamwork, and sportsmanship in a fun and supportive environment. Registration open year-round.",
    schedule: "sat",
  },
  {
    id: 5,
    title: "iCode Sammamish Intro to Coding",
    type: "Workshop",
    date: "Friday, Feb 5, 2026",
    time: "6:00 PM - 8:00 PM",
    location: "iCode Sammamish",
    address: "22840 NE 8th St, Sammamish, WA 98074",
    cost: "$15",
    tags: ["Arts", "Education", "Community"],
    image: "https://images.unsplash.com/photo-1610986603166-f78428624e76?w=800",
    latitude: 47.616653,
    longitude: -122.034168,
    description: "A beginner-friendly two-hour coding workshop introducing fundamental programming concepts using hands-on projects. Perfect for students and adults with no prior experience. Participants will build their first interactive program and leave with resources to keep learning.",
    schedule: "2026-02-05",
  },
  {
    id: 6,
    title: "Senior Fitness Classes",
    type: "Program",
    date: "Mondays & Wednesdays",
    time: "9:00 AM - 10:00 AM",
    location: "Sammamish YMCA",
    address: "831 228th Ave SE, Sammamish, WA 98075",
    cost: "Free",
    tags: ["Seniors", "Health", "Fitness"],
    image: "https://images.unsplash.com/photo-1764173040171-57f79264b358?w=800",
    latitude: 47.616653,
    longitude: -122.034168,
    description: "Low-impact fitness classes designed specifically for adults 55 and older. Led by certified instructors, sessions include gentle stretching, balance exercises, and light cardio to improve mobility and overall wellbeing. No registration required — just show up!",
    schedule: "mon-wed",
  },
  {
    id: 7,
    title: "Evans Creek Preserve Work Party",
    type: "Volunteering",
    date: "Saturday, March 14, 2026",
    time: "9:00 AM - 1:00 PM",
    location: "Evans Creek Preserve - North Entrance",
    address: "3650 Sahalee Way NE, Sammamish, WA 98074",
    cost: "Free",
    tags: ["Environment", "Outdoors", "Volunteering"],
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Evans_Creek_Preserve_Boardwalk.jpg/960px-Evans_Creek_Preserve_Boardwalk.jpg?_=20170206012550",
    latitude: 47.6433,
    longitude: -122.0461,
    description: "Partner with the Washington Trails Association for a day of essential trail maintenance. We will focus on improving drainage and clearing invasive species to keep the Evans Creek ecosystem healthy and accessible.",
    schedule: "2026-03-14",
  },
  {
    id: 8,
    title: "Sammamish Library Story Time",
    type: "Program",
    date: "Every Tuesday",
    time: "10:30 AM - 11:15 AM",
    location: "Sammamish Library - Children's Area",
    address: "825 228th Ave SE, Sammamish, WA 98075",
    cost: "Free",
    tags: ["Youth", "Education", "Family"],
    image: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=800",
    latitude: 47.6021,
    longitude: -122.0382,
    description: "A fun and interactive session designed for toddlers and preschoolers. KCLS librarians lead children through engaging stories, songs, and rhymes to build early literacy skills and a love for reading.",
    schedule: "tue",
  },
  {
    id: 9,
    title: "Soaring Eagle Night Run",
    type: "Event",
    date: "Friday, April 17, 2026",
    time: "8:00 PM - 10:00 PM",
    location: "Soaring Eagle Regional Park",
    address: "26015 E Main Dr, Sammamish, WA 98074",
    cost: "$25",
    tags: ["Sports", "Outdoors", "Fitness"],
    image: "https://images.unsplash.com/photo-1456613820599-bfe244172af5?q=80&w=1748&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    latitude: 47.6292,
    longitude: -122.0015,
    description: "Experience the thrill of trail running under the stars. This guided 5K night run takes participants through the winding forest trails of Soaring Eagle. Headlamps and high-visibility gear are mandatory.",
    schedule: "2026-04-17",
  },
  {
    id: 10,
    title: "Teen Tech Night: Robotics",
    type: "Workshop",
    date: "Monday, Feb 23, 2026",
    time: "4:00 PM - 6:00 PM",
    location: "Eastlake Senior High - STEM Lab",
    address: "400 228th Ave NE, Sammamish, WA 98074",
    cost: "Free",
    tags: ["Youth", "Education", "Technology"],
    image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800",
    latitude: 47.6144,
    longitude: -122.0375,
    description: "Open to all high school students interested in engineering. Work with the Eastlake Robotics team to learn basic CAD design and assembly. No prior experience needed — snacks provided.",
    schedule: "2026-02-23",
  },
  {
    id: 11,
    title: "Pine Lake Summer Concert",
    type: "Event",
    date: "Every Thursday",
    time: "6:30 PM - 8:30 PM",
    location: "Pine Lake Park Stage",
    address: "2401 228th Ave SE, Sammamish, WA 98075",
    cost: "Free",
    tags: ["Arts", "Music", "Family"],
    image: "https://images.unsplash.com/photo-1719479757967-c61fd530c625?q=80&w=2214&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    latitude: 47.5872,
    longitude: -122.0385,
    description: "The city's signature summer series. Bring a picnic blanket and enjoy live performances from local Pacific Northwest bands. Genres range from jazz to indie rock in a beautiful lakeside setting.",
    schedule: "thu",
  },
  {
    id: 12,
    title: "Sammamish Food Bank Intake",
    type: "Volunteering",
    date: "Mon-Wed",
    time: "8:00 AM - 12:00 PM",
    location: "Sammamish Food Bank",
    address: "22520 SE 24th St, Sammamish, WA 98075",
    cost: "Free",
    tags: ["Community", "Social", "Volunteering"],
    image: "https://images.unsplash.com/photo-1593113598332-cd288d649433?w=800",
    latitude: 47.5878,
    longitude: -122.0405,
    description: "Assist with sorting and organizing food donations for local families in need. Volunteers help with stock rotation, quality control, and preparing distribution boxes.",
    schedule: "mon-wed",
  },
  {
    id: 13,
    title: "Community Garden Planting Day",
    type: "Event",
    date: "Saturday, May 9, 2026",
    time: "10:00 AM - 2:00 PM",
    location: "Lower Sammamish Commons",
    address: "801 228th Ave SE, Sammamish, WA 98075",
    cost: "Free",
    tags: ["Environment", "Community", "Education"],
    image: "https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=800",
    latitude: 47.6014,
    longitude: -122.0380,
    description: "Help kick off the spring growing season. Join neighbors in planting the communal vegetable beds. Expert gardeners will be on hand to provide tips on organic soil health and companion planting.",
    schedule: "2026-05-09",
  },
  {
    id: 14,
    title: "Sustainability Fair",
    type: "Event",
    date: "Friday, June 5, 2026",
    time: "11:00 AM - 4:00 PM",
    location: "Sammamish Commons Plaza",
    address: "801 228th Ave SE, Sammamish, WA 98075",
    cost: "Free",
    tags: ["Environment", "Education", "Government"],
    image: "https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?w=800",
    latitude: 47.6014,
    longitude: -122.0380,
    description: "Learn how to live more sustainably in Sammamish. Featuring booths from local environmental groups, solar energy experts, and zero-waste vendors. Electric vehicle displays on-site.",
    schedule: "2026-06-05",
  },
  {
    id: 15,
    title: "Skyline HS Drama Production",
    type: "Event",
    date: "Saturday, March 21, 2026",
    time: "7:00 PM - 9:30 PM",
    location: "Skyline High School Theater",
    address: "1122 228th Ave SE, Sammamish, WA 98075",
    cost: "$15",
    tags: ["Arts", "Youth", "Education"],
    image: "https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?w=800",
    latitude: 47.5995,
    longitude: -122.0381,
    description: "Support local student theater at the Skyline Performing Arts Center. This season features a modern reimagining of a classic play, entirely directed and produced by the drama department.",
    schedule: "2026-03-21",
  },
  {
    id: 16,
    title: "Beaver Lake Park Bird Walk",
    type: "Event",
    date: "Saturday, Feb 14, 2026",
    time: "8:00 AM - 10:00 AM",
    location: "Beaver Lake Park - Pavilion",
    address: "25201 SE 24th St, Sammamish, WA 98075",
    cost: "Free",
    tags: ["Environment", "Outdoors", "Education"],
    image: "https://images.unsplash.com/photo-1721736742833-8ffbf1f14349?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    latitude: 47.5875,
    longitude: -122.0055,
    description: "Join the Eastside Audubon Society for a morning of birdwatching. Discover the diverse species that call Beaver Lake home during the winter months. Binoculars available for loan.",
    schedule: "2026-02-14",
  },
  {
    id: 17,
    title: "Small Business Networking",
    type: "Event",
    date: "Every Wednesday",
    time: "8:30 AM - 9:30 AM",
    location: "Metropolitan Market Café",
    address: "301 228th Ave SE, Sammamish, WA 98074",
    cost: "Free",
    tags: ["Business", "Networking", "Professional"],
    image: "https://images.unsplash.com/photo-1515162305285-0293e4767cc2?w=800",
    latitude: 47.6105,
    longitude: -122.0380,
    description: "A weekly informal gathering for Sammamish business owners and entrepreneurs. Share resources, discuss market trends, and build local professional partnerships over coffee.",
    schedule: "wed",
  },
  {
    id: 18,
    title: "Stormwater Workshop",
    type: "Workshop",
    date: "Tuesday, April 21, 2026",
    time: "6:30 PM - 8:00 PM",
    location: "City Hall Council Chambers",
    address: "801 228th Ave SE, Sammamish, WA 98075",
    cost: "Free",
    tags: ["Environment", "Education", "Government"],
    image: "https://images.unsplash.com/photo-1414490929659-9a12b7e31907?w=800",
    latitude: 47.6014,
    longitude: -122.0380,
    description: "Learn how to manage runoff on your property and protect the Sammamish watershed. City experts will discuss rain gardens, pervious surfaces, and native planting techniques.",
    schedule: "2026-04-21",
  },
  {
    id: 19,
    title: "Youth Art in the Park",
    type: "Program",
    date: "Every Saturday",
    time: "1:00 PM - 3:00 PM",
    location: "Ebright Creek Park",
    address: "1317 212th Ave SE, Sammamish, WA 98075",
    cost: "$10/session",
    tags: ["Youth", "Arts", "Recreation"],
    image: "https://images.unsplash.com/photo-1598997853707-6566fec09245?q=80&w=1178&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    latitude: 47.5972,
    longitude: -122.0565,
    description: "Open-air art classes for elementary school students. Each week explores a new medium, from charcoal sketching to watercolor landscapes, inspired by the park's natural beauty.",
    schedule: "sat",
  },
  {
    id: 20,
    title: "Sammamish Symphony Concert",
    type: "Event",
    date: "Sunday, March 8, 2026",
    time: "2:00 PM - 4:00 PM",
    location: "Eastlake Performing Arts Center",
    address: "400 228th Ave NE, Sammamish, WA 98074",
    cost: "$20",
    tags: ["Arts", "Music", "Community"],
    image: "https://images.unsplash.com/photo-1613142659418-718b2ae6940d?q=80&w=1805&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    latitude: 47.6144,
    longitude: -122.0375,
    description: "The Sammamish Symphony Orchestra presents 'Spring Awakening.' A professional-grade performance featuring classical masterpieces and contemporary compositions by local musicians.",
    schedule: "2026-03-08",
  },
  {
    id: 21,
    title: "Plateau Wine Tasting Series",
    type: "Event",
    date: "Every Friday",
    time: "5:00 PM - 7:00 PM",
    location: "Plateau Wine & Spirits",
    address: "700 228th Ave NE, Sammamish, WA 98074",
    cost: "$15",
    tags: ["Social", "Food", "Networking"],
    image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800",
    latitude: 47.6171,
    longitude: -122.0378,
    description: "Discover Washington’s finest vineyards. Each week features a different regional winery with guided tastings and pairings in an intimate community setting.",
    schedule: "fri",
  },
  {
    id: 22,
    title: "Teen Lounge Night",
    type: "Program",
    date: "Every Friday",
    time: "7:00 PM - 10:00 PM",
    location: "Sammamish YMCA - Teen Center",
    address: "831 228th Ave SE, Sammamish, WA 98075",
    cost: "Free",
    tags: ["Youth", "Social", "Community"],
    image: "https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=800",
    latitude: 47.6018,
    longitude: -122.0372,
    description: "A safe and engaging space for middle and high school students. Includes video games, table tennis, and structured group activities led by YMCA youth coordinators.",
    schedule: "fri",
  },
  {
    id: 23,
    title: "Rotary Club of Sammamish",
    type: "Event",
    date: "Every Thursday",
    time: "7:30 AM - 8:30 AM",
    location: "The Plateau Club",
    address: "25625 E Plateau Dr, Sammamish, WA 98074",
    cost: "Free (Guests)",
    tags: ["Community", "Volunteering", "Networking"],
    image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    latitude: 47.6322,
    longitude: -121.9985,
    description: "Service-minded professionals gather weekly to plan local and international community service projects. Guests are welcome to learn about upcoming volunteer initiatives.",
    schedule: "thu",
  },
  {
    id: 24,
    title: "Klahanie Park Fitness Trail",
    type: "Program",
    date: "Mondays & Wednesdays",
    time: "6:00 AM - 7:00 AM",
    location: "Klahanie Park",
    address: "25000 SE Klahanie Blvd, Issaquah, WA 98029",
    cost: "Free",
    tags: ["Health", "Fitness", "Outdoors"],
    image: "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=800",
    latitude: 47.5702,
    longitude: -122.0085,
    description: "A guided bootcamp-style fitness session utilizing the park's outdoor exercise equipment. Focuses on functional strength and interval training for all fitness levels.",
    schedule: "mon-wed",
  },
  {
    id: 25,
    title: "Sammamish Arts Commission Meeting",
    type: "Event",
    date: "Monday, March 2, 2026",
    time: "6:30 PM - 8:00 PM",
    location: "City Hall Room 111",
    address: "801 228th Ave SE, Sammamish, WA 98075",
    cost: "Free",
    tags: ["Arts", "Government", "Community"],
    image: "https://images.unsplash.com/photo-1571624436279-b272aff752b5?q=80&w=1744&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    latitude: 47.6014,
    longitude: -122.0380,
    description: "Public meeting to discuss upcoming public art installations and cultural events in the city. Residents are encouraged to provide feedback on city art grants and initiatives.",
    schedule: "2026-03-02",
  },
  {
    id: 26,
    title: "Eastlake HS Football Game",
    type: "Event",
    date: "Friday, Sept 25, 2026",
    time: "7:00 PM - 10:00 PM",
    location: "Eastlake Stadium",
    address: "400 228th Ave NE, Sammamish, WA 98074",
    cost: "$10",
    tags: ["Sports", "Youth", "Family"],
    image: "https://images.unsplash.com/photo-1566577739112-5180d4bf9390?w=800",
    latitude: 47.6144,
    longitude: -122.0375,
    description: "Come support the Wolves under the Friday night lights. A classic community event featuring local high school competition, halftime performances, and a lively student section.",
    schedule: "2026-09-25",
  },
];
